### ISSUE TITLE
preprocess issue

### ISSUE THREAD

**Issue by CoderChen01** [AgentMaker/PaTTA#1]
# issue 1
## 当我将crop_size调至(1024,512), 报错
Traceback (most recent call last):
  File "PaTTA/tools/seg.py", line 41, in <module>
    main(args.batch_size, imgs_list, args.crop_size)
  File "PaTTA/tools/seg.py", line 26, in main
    tensor_img = tta_model(tensor_img)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/patta/wrappers.py", line 39, in forward
    augmented_output = self.model(augmented_image, *args)[0]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/io.py", line 1170, in __i_m_p_l__
    return _run_dygraph(self, input, program_holder)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/io.py", line 733, in _run_dygraph
    'is_test': instance._is_test
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [16, 48, 128, 256] and the shape of Y = [16, 48, 384, 384]. Received [128] in X is not equal to [384] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
  [operator < elementwise_add > error]  [operator < run_program > error]
## 事实上修改任意crop_size都报错，但是改为1536,1536即数据集的图片尺寸，上述错误解决，但是issue2出现
# issue 2
Traceback (most recent call last):
  File "PaTTA/tools/seg.py", line 41, in <module>
    main(args.batch_size, imgs_list, args.crop_size)
  File "PaTTA/tools/seg.py", line 26, in main
    tensor_img = tta_model(tensor_img)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/patta/wrappers.py", line 39, in forward
    augmented_output = self.model(augmented_image, *args)[0]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/io.py", line 1170, in __i_m_p_l__
    return _run_dygraph(self, input, program_holder)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/io.py", line 733, in _run_dygraph
    'is_test': instance._is_test
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [16, 512, 384, 384], X's size = 1207959552, 'shape' is [1, 512, 147456], the capacity of 'shape' is 75497472.
  [Hint: Expected capacity == in_size, but received capacity:75497472 != in_size:1207959552.] (at /paddle/paddle/fluid/operators/reshape_op.cc:222)
  [operator < reshape2 > error]  [operator < run_program > error]

**Comment by WhiteFireFox** [comment]
头秃，因为我们训练的时候是(256, 256)输入的，所以整体框架暂时只支持裁剪至正方形导入使用。

**Comment by WhiteFireFox** [comment]
后续我们会修复这个bug，因为涉及整体的改动，可能工期会比较长

**Comment by CoderChen01** [comment]
> 头秃，因为我们训练的时候是(256, 256)输入的，所以整体框架暂时只支持裁剪至正方形导入使用。
这和这个框架有关系吗，你这基本思路不是加载**我的模型**，然后对预测集做不同转换，然后得到结果，求平均吗

**Comment by CoderChen01** [comment]
512,512也不行呀&nbsp; 那个384,384不知道啥，好像是写死的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhihao ***@***.***&gt;; 
发送时间: 2021年3月14日(星期天) 中午1:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AgentMaker/PaTTA] preprocess issue (#1)





 
头秃，因为我们训练的时候是(256, 256)输入的，所以整体框架暂时只支持裁剪至正方形导入使用。

**Comment by WhiteFireFox** [comment]
512,512也是可以的啊，改seg.py下面的parser.add_argument('--crop_size', type=tuple, default=(224, 224))这个就好

**Comment by WhiteFireFox** [comment]
> > 头秃，因为我们训练的时候是(256, 256)输入的，所以整体框架暂时只支持裁剪至正方形导入使用。
> 
> 这和这个框架有关系吗，你这基本思路不是加载**我的模型**，然后对预测集做不同转换，然后得到结果，求平均吗

是的，但是里面封装的function得改一下

**Comment by CoderChen01** [comment]
> 512,512也是可以的啊，改seg.py下面的parser.add_argument('--crop_size', type=tuple, default=(224, 224))这个就好

![image](https://user-images.githubusercontent.com/61137732/111058317-c8ac6900-84c8-11eb-9760-62b3a5a3bc07.png)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [16, 48, 128, 128] and the shape of Y = [16, 48, 384, 384]. Received [128] in X is not equal to [384] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
  [operator < elementwise_add > error]  [operator < run_program > error]

**Comment by WhiteFireFox** [comment]
> > > 头秃，因为我们训练的时候是(256, 256)输入的，所以整体框架暂时只支持裁剪至正方形导入使用。
> > 
> > 
> > 这和这个框架有关系吗，你这基本思路不是加载**我的模型**，然后对预测集做不同转换，然后得到结果，求平均吗
> 
> 是的，但是里面封装的function得改一下


> > 512,512也是可以的啊，改seg.py下面的parser.add_argument('--crop_size', type=tuple, default=(224, 224))这个就好
> 
> ![image](https://user-images.githubusercontent.com/61137732/111058317-c8ac6900-84c8-11eb-9760-62b3a5a3bc07.png)
> ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [16, 48, 128, 128] and the shape of Y = [16, 48, 384, 384]. Received [128] in X is not equal to [384] in Y at i:2.
> [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
> [operator < elementwise_add > error] [operator < run_program > error]

![](https://user-images.githubusercontent.com/57762833/111058417-8c2d3d00-84c9-11eb-85ac-9fbf49539f4b.JPG)
![](https://user-images.githubusercontent.com/57762833/111058430-97806880-84c9-11eb-9420-15a0e3ad7d59.JPG)
![](https://user-images.githubusercontent.com/57762833/111058840-34440580-84cc-11eb-999f-8b78b2e8caf6.JPG)
我刚刚用小号fork了试了一下，好像能跑通

**Comment by WhiteFireFox** [comment]
> > > > 头秃，因为我们训练的时候是(256, 256)输入的，所以整体框架暂时只支持裁剪至正方形导入使用。
> > > 
> > > 
> > > 这和这个框架有关系吗，你这基本思路不是加载**我的模型**，然后对预测集做不同转换，然后得到结果，求平均吗
> > 
> > 
> > 是的，但是里面封装的function得改一下
> 
> > > 512,512也是可以的啊，改seg.py下面的parser.add_argument('--crop_size', type=tuple, default=(224, 224))这个就好
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/61137732/111058317-c8ac6900-84c8-11eb-9760-62b3a5a3bc07.png)
> > ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [16, 48, 128, 128] and the shape of Y = [16, 48, 384, 384]. Received [128] in X is not equal to [384] in Y at i:2.
> > [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
> > [operator < elementwise_add > error] [operator < run_program > error]
> 
> ![](https://user-images.githubusercontent.com/57762833/111058417-8c2d3d00-84c9-11eb-85ac-9fbf49539f4b.JPG)
> ![](https://user-images.githubusercontent.com/57762833/111058430-97806880-84c9-11eb-9420-15a0e3ad7d59.JPG)
> ![](https://user-images.githubusercontent.com/57762833/111058840-34440580-84cc-11eb-999f-8b78b2e8caf6.JPG)
> 我刚刚用小号fork了试了一下，好像能跑通

您可以先再尝试下，非常感谢您的反馈

**Comment by CoderChen01** [comment]
我晚些把我的iter_1000的静态模型发给你  你debug一下  ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月14日(星期天) 中午1:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AgentMaker/PaTTA] preprocess issue (#1)

**Comment by yangrisheng** [comment]
解决了吗
