### ISSUE TITLE
【PaddlePaddle Hackathon】97 新增图像数据增强算法 

### ISSUE THREAD

**Issue by GT-ZhangAcer** [AgentMaker/PaTTA#5]
（此 ISSUE 为 PaddlePaddle Hackathon 活动的任务 ISSUE，更多详见[PaddlePaddle Hackathon](https://www.paddlepaddle.org.cn/PaddlePaddleHackathon?fr=agentmakerg)）

PaTTA 是一个致力于让模型表现更加稳定的飞桨模型测试增强工具箱，其原理为在测试时对要推理的数据进行增强，通过投票形式选出更稳健的推理结果。

【任务说明】

- 任务标题：新增图像数据增强算法

- 技术标签：Python

- 任务难度：简单

- 详细描述：数据增强是一种比较有效的模型能力提升方式，更多的组合可使得模型在训练时更加关注目标特征，从而进一步提升模型成绩。目前 PaTTA 中仅具备高频的图像数据增强算法。本这个项目，需要你新增不低于5个图像方向的数据增强算法，并且这些算法能够略微、显著提升推理成绩，以提升 PaTTA 可用性。

【提交内容】

- 项目 PR 到 [PaTTA](https://github.com/AgentMaker/PaTTA)

- 技术说明文档

【项目技术要求】

- 具有基础的 Python 开发能力

- 有过在深度学习中使用图像增强的经历

**Comment by zackzhao1** [comment]
这个任务的数据增强方法是必须在tensor上实现吗，常见的在numpy上做数据增强后转tensor可以吗

**Comment by GT-ZhangAcer** [comment]
> 
> 
> 这个任务的数据增强方法是必须在tensor上实现吗，常见的在numpy上做数据增强后转tensor可以吗

非必须，和普通的数据集增强保持一致即可
